### ISSUE TITLE
快速入门有一处笔误

### ISSUE THREAD

**Issue by Ahtaler** [u-u-z/kigurumi#9]
https://github.com/u-u-z/kigurumi/blob/main/get-start.md#%E8%80%90%E5%BF%83%E7%AD%89%E5%BE%85
“这需要一些乃心”

**Comment by u-u-z** [comment]
https://github.com/u-u-z/kigurumi/commit/b3d457d2d4193b810653d0fc582411b3c772e8af
fixed! thx~
